#!/usr/bin/env node
'use strict';
// UserPromptSubmit reminder. Prompt 1 of a session (and every 30th after, so
// the rules survive context compaction) injects the gate matrix and the FULL
// contents of rules/RULES.md -- the one defined exemption from the 500-char
// injection cap. Every other prompt gets a one-line anchor (< 500 chars):
// current phase, pending gate, verify-lock status, and background dispatches.
// Session prompt counts live in spearhead/.remind-state.json.
//
// The project directory resolves per the fallback chain: explicit
// cwd/project field in the payload -> a tool-input path -> the project-hint
// JSON guard.js leaves in KIMI_PLUGIN_ROOT. NEVER process.cwd() (kimi-code
// runs hooks with the plugin root as cwd). No resolvable spearhead/ dir:
// silent no-op.
//
// Loaded both by direct execution and by kimi-code's __plugin_run_node
// require() shim; runs on load unless SPEARHEAD_HOOK_LIB=1 (library/tests).

const wasLib = !!process.env.SPEARHEAD_HOOK_LIB;
process.env.SPEARHEAD_HOOK_LIB = '1'; // import the invariant module's library half
const fs = require('node:fs');
const path = require('node:path');
const inv = require(path.join(__dirname, 'validate-state.js'));

const RULES_PATH = path.join(__dirname, '..', 'rules', 'RULES.md');
const REFRESH_EVERY = 30; // full rules on prompts 1, 31, 61, ...
const MAX_TRACKED_SESSIONS = 20;
// A session that has been idle this long is treated as new (full rules
// again). This matters most for the 'default' fallback key below.
const SESSION_IDLE_MS = 12 * 60 * 60 * 1000;

// Some runtimes do not put a session id on the hook payload at all. Falling
// back to "every prompt is the first prompt" would inject the full rules on
// EVERY user message, so instead all such prompts share one 'default'
// counter in .remind-state.json -- the cadence is managed by state, not by
// the payload's generosity. Idle expiry above keeps 'default' from starving
// a genuinely new session of its prompt-1 rules.
function sessionKeyFrom(input) {
  for (const k of ['session_id', 'sessionId', 'session', 'conversation_id', 'chat_id']) {
    if (input && typeof input[k] === 'string' && input[k]) return input[k];
  }
  return 'default';
}

// The full injection: a two-line header plus rules/RULES.md verbatim. The
// rules content is read from the file at emit time, so the single-source
// guarantee is mechanical; remind.test.js asserts byte identity.
function fullMessage() {
  let rules;
  try {
    rules = fs.readFileSync(RULES_PATH, 'utf8');
  } catch {
    rules = '(rules/RULES.md unreadable -- reinstall the spearhead plugin)\n';
  }
  const important =
    '\n<important>No extra commentary unless necessary. Response temperature is 0.2. This does not apply to code generated by AI.</important>\n';
  return (
    'This project uses the spearhead workflow. Gates are hard: a phase skill refuses until the previous gate is satisfied, spearhead/status.yml is mutated only through scripts/state.js, and nothing self-certifies. The canonical rules and gate matrix follow (from rules/RULES.md):\n\n' +
    rules +
    important
  );
}

// One-line anchor, kept under 500 characters.
function anchor(projectDir) {
  let detail = 'no active attack yet -- /spearhead:understand starts one';
  try {
    const text = fs.readFileSync(path.join(projectDir, 'spearhead', 'status.yml'), 'utf8');
    const { status, errors } = inv.parseStatus(text);
    if (errors.length === 0) detail = describe(status);
  } catch {
    // keep the generic anchor
  }
  const line = `spearhead active: ${detail}. Gates apply; state via scripts/state.js only.\n`;
  const search = 'Before reading source files to answer a question, try the spearhead-knowledge search tool first.\n';
  const important =
    '<important>No extra commentary unless necessary. Response temperature is 0.2. This does not apply to code generated by AI.</important>\n';
  return (line.length <= 500 ? line : line.slice(0, 496) + '...\n') + search + important;
}

function describe(s) {
  const tasks = s.tasks || [];
  const allDone = tasks.length > 0 && tasks.every((t) => t.status === 'done');
  let phase;
  if (s.phases.understand !== 'approved') phase = 'understand';
  else if (s.phases.recon !== 'complete') phase = 'recon';
  else if (s.phases.design !== 'approved') phase = 'design';
  else if (s.phases.plan !== 'approved') phase = 'plan';
  else if (!allDone) phase = 'execute/verify';
  else if (s.phases.ship !== 'complete') phase = 'ship';
  else if (s.phases.retro !== 'complete') phase = 'retro';
  else phase = 'complete';
  const parts = [`${s.attack.id} ${s.attack.state}, phase=${phase}`];
  if (s.verify_lock) parts.push(`verify_lock=${s.verify_lock}`);
  const bg = tasks.filter((t) => t.status === 'in_progress' && t.mode === 'background').map((t) => t.id);
  if (bg.length) parts.push(`bg: ${bg.join(', ')}`);
  const blocked = tasks.filter((t) => t.status === 'blocked').map((t) => t.id);
  if (blocked.length) parts.push(`blocked: ${blocked.join(', ')} (/spearhead:unblock)`);
  return parts.join('; ');
}

// Returns the number of prompts seen so far in this session (0 for the
// first), updating the state file. Any failure means "first prompt".
function promptIndex(statePath, sessionId) {
  let state = { sessions: {} };
  try {
    const parsed = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    if (parsed && typeof parsed.sessions === 'object' && parsed.sessions !== null) state = parsed;
  } catch {
    // missing or corrupt state: treat as fresh
  }
  const entry = state.sessions[sessionId] || { count: 0, at: 0 };
  let index = entry.count;
  if (entry.at && Date.now() - entry.at > SESSION_IDLE_MS) index = 0; // idle: treat as a new session
  state.sessions[sessionId] = { count: index + 1, at: Date.now() };
  const ids = Object.keys(state.sessions);
  if (ids.length > MAX_TRACKED_SESSIONS) {
    ids
      .sort((a, b) => (state.sessions[a].at || 0) - (state.sessions[b].at || 0))
      .slice(0, ids.length - MAX_TRACKED_SESSIONS)
      .forEach((id) => delete state.sessions[id]);
  }
  try {
    fs.writeFileSync(statePath, JSON.stringify(state) + '\n');
  } catch {
    // read-only project: fall back to full message every prompt
  }
  return index;
}

// Fallback chain for the project directory (rule 12b). Never process.cwd().
function resolveProjectDir(input) {
  if (input && typeof input.cwd === 'string' && input.cwd) return input.cwd;
  if (input && typeof input.project_dir === 'string' && input.project_dir) return input.project_dir;
  const args = (input && input.tool_input) || {};
  for (const p of [args.file_path, args.path, args.notebook_path]) {
    const m = typeof p === 'string' && p.replace(/\\/g, '/').match(/^(.*?)\/spearhead\//);
    if (m) return m[1];
  }
  if (process.env.KIMI_PLUGIN_ROOT) {
    try {
      const hint = JSON.parse(fs.readFileSync(path.join(process.env.KIMI_PLUGIN_ROOT, '.spearhead-project.json'), 'utf8'));
      if (hint && typeof hint.projectDir === 'string') return hint.projectDir;
    } catch {
      // no hint: fall through
    }
  }
  return null;
}

function main() {
  let raw = '';
  process.stdin.on('data', (chunk) => (raw += chunk));
  process.stdin.on('end', () => {
    let input = null;
    try {
      input = JSON.parse(raw);
    } catch {
      // no usable stdin: no project dir source below, so no-op
    }
    const projectDir = resolveProjectDir(input);
    if (projectDir === null) process.exit(0);
    const spearheadDir = path.join(projectDir, 'spearhead');
    if (!fs.existsSync(spearheadDir)) process.exit(0);
    const index = promptIndex(path.join(spearheadDir, '.remind-state.json'), sessionKeyFrom(input));
    process.stdout.write(index % REFRESH_EVERY === 0 ? fullMessage() : anchor(projectDir));
  });
}

module.exports = { fullMessage, anchor, describe, resolveProjectDir, promptIndex, sessionKeyFrom, REFRESH_EVERY, RULES_PATH, main };
if (!wasLib) main();
